### ISSUE TITLE
python 3.13: AttributeError: 'EventQueue' object has no attribute '_last_item' when using "watch"

### ISSUE THREAD

**Issue by stevleibelt** [Bogdanp/dramatiq#717]
## Checklist

* [x] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What version of Python are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Self build docker image with `python:3.13-bookworm` as source.

## What version of Dramatiq are you using?

Was able to reproduce this issue with version [1.18.0](https://github.com/Bogdanp/dramatiq/releases/tag/v1.18.0) and [1.17.1](https://github.com/Bogdanp/dramatiq/releases/tag/v1.17.1).

## What version of Python are you using?

Python 3.13.5

## What did you do?

* Started the workers with `env PYTHONPATH=/app dramatiq-gevent context.first.tasks context.second.tasks -p 2 -t 4 --watch /app --watch-use-polling`
* Made changes by adding a comment to the file in `context/first/tasks.py`
* Saved the changes

## What did you expect would happen?

A fine reload of the code.

## What happened?

Code is not reloaded. The following exception trace is shown in an open shell running `docker compose logs -f`.

```bash
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/watchdog/observers/api.py", line 158, in run
    self.queue_events(self.timeout)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/watchdog/observers/polling.py", line 100, in queue_events
    self.queue_event(FileModifiedEvent(src_path))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/watchdog/observers/api.py", line 143, in queue_event
    self._event_queue.put((event, self.watch))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/watchdog/utils/bricks.py", line 79, in put
    if self._last_item is None or item != self._last_item:
       ^^^^^^^^^^^^^^^
AttributeError: 'EventQueue' object has no attribute '_last_item'
```

If I restart the container, the code change is accepted and no error is occurring.

**Comment by LincolnPuzey** [comment]
Are you copying the source code into the docker image? i.e. using `COPY` in the dockerfile?
or are you mounting the source code as a volume?

If it is the first option, then I suspect the `--watch` running in the docker container is unable to see the changes to the source code in the original location.
If it is the second option, then I don't know how `--watch` would work with that.

If you are able to share your Dockerfile and/or compose file, that will help us help you :)

**Comment by stevleibelt** [comment]
@LincolnPuzey thanks for your response.

I will try to share a simplified version of my `Dockerfile` and `compose.yml`.

> Are you copying the source code into the docker image? i.e. using COPY in the dockerfile?
I am mounting it in.   
`--watch`/this setup was working fine with previous python versions.

## Docker compose yaml file

```yaml
  worker-dev:
    build:
      context: .
      dockerfile: app_cli.Docker
    command:
      - "/app/bin/run_cli.sh"
      - "shared"
      - "start-workers"
      - "--watch"
    container_name: worker-dev
    environment:
      ENV: dev
      TZ: "Europe/Berlin"
    restart: always
    profiles:
      - dev
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    user: "${UID?}:${GID?}"
```

## Docker file named `app_cli.Docker`

```bash
FROM python:3.13-bookworm

COPY requirements.txt /tmp/

# default packages
RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    curl \
    gnupg2 \
    mariadb-client \
    libmariadb-dev \
    postgresql-client-15 \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

# python packages
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt
```

**Comment by LincolnPuzey** [comment]
> If it is the second option, then I don't know how --watch would work with that

I only say this because I don't know what mechanism watchdog is using, and if it would be expected to work when the 'watching' is happening inside a docker container, and the change is being applied outside the container.

Has this setup ever worked? Did you change something (e.g. `watchdog` version)? That could be a useful clue, and/or a way to get back to a working setup in the meantime.

**Comment by stevleibelt** [comment]
I've switched workstation in-between but nothing serious beside that.
Linux itself is still an arch linux with ongoing changes.
The area that starts the worker and consumes the actors code has not changed. Meaning I have no idea how to come closer to an older and working setup exception going back to older python- and dramatiq-version.

Based on your thoughts, the filesystem is notifying a change that has happened. This signals goes to the watchdog which acts as a subscriber.
The watchdog gets the change, at least that is my explanation why I am able to constantly trigger this error.

**Comment by LincolnPuzey** [comment]
I was able to reproduce with the following minimal app:

`docker-compose.yml`:
```yaml
services:
  app:
    pull_policy: build
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.13-bookworm
        RUN pip install --no-cache-dir "watchdog==6.0.0" "dramatiq[watch]==1.18.0" "gevent==25.5.1" "watchdog_gevent==0.2.1"
        WORKDIR /
    command: ["dramatiq-gevent", "app", "--watch", "/app", "--watch-use-polling"]
    volumes:
      - ./app:/app
```

And `app/__init__.py`:
```python3
import dramatiq
import dramatiq.brokers.stub

broker = dramatiq.brokers.stub.StubBroker()
dramatiq.set_broker(broker)

@dramatiq.actor(broker=broker)
def hello_world():
    print("hello world")
```

Using the compose file to build and run the container, and then editing the python source, gives me the same `AttributeError: 'EventQueue' object has no attribute '_last_item'`

Not sure what the root cause is, but a workaround for me was changing `dramatiq-gevent` in the command to regular `dramatiq`. Not sure if that is viable for you.
